apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: database-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: database-service-account
  namespace: default
roleRef:
  kind: Role
  name: database-role
  apiGroup: rbac.authorization.k8s.io
