apiVersion: v1
kind: ServiceAccount
metadata:
  name: minimal-service-account
  namespace: default
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: minimal-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
  resourceNames: ["specific-pod-name"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minimal-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: minimal-service-account
  namespace: default
roleRef:
  kind: Role
  name: minimal-role
  apiGroup: rbac.authorization.k8s.io
